# Generated by Django 4.0.3 on 2022-04-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_catagory_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcatagory',
            new_name='subcategory',
        ),
    ]
